#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZPREZTODIR=$HOME/dotfiles
# Source Prezto.
if [[ -s "${ZPREZTODIR:-$HOME}/zprezto/init.zsh" ]]; then
  source "${ZPREZTODIR:-$HOME}/zprezto/init.zsh"
fi

# Customize to your needs...
## load aliases
source ~/.sh_conf/aliases
[ -f ~/.local_conf/localrc ] && source ~/.local_conf/localrc

# Ctrl-PとCtrl-Nで前方一致検索
autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

## prompt theme
autoload -Uz promptinit
promptinit
prompt damoekri

