#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZPREZTODIR=$HOME/dotfiles
# Source Prezto.
if [[ -s "${ZPREZTODIR:-$HOME}/zprezto/init.zsh" ]]; then
  source "${ZPREZTODIR:-$HOME}/zprezto/init.zsh"
fi

# Customize to your needs...
## load aliases
source ~/.config/shell/alias
[ -f ~/.config/shell/rc.local ] && source ~/.config/shell/rc.local

## prompt theme
autoload -Uz promptinit
promptinit
prompt damoekri
# PROMPT='%F{033}${_prompt_damoekri_pwd}%f${editor_info[keymap]} '
PROMPT='%F{038}[${HOST:0:4}] %~
%f${editor_info[keymap]} '

if [[ -t 0 ]]; then
  stty stop undef
  stty start undef
fi
