#!/bin/zsh

local f=~/.custom_list
local lines=("${(@f)$(egrep "$2" "$f")}")
local e=("${"${@}"}")
local upd_lines=()
for v in "${lines[@]}"; do
  if [[ $e != $v ]]; then
    upd_lines+=($v)
  fi
done
: > $f
printf "%s\n" ${upd_lines[@]} | sort -u >> $f
