[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_source = 'source ~/.config/nvim/plugins/vim-easymotion.vim'
on_event = 'VimEnter'
depends = ['vim-submode']

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_source = 'source ~/.config/nvim/plugins/vim-gitgutter.vim'
on_event = 'VimEnter'
depends = ['vim-submode']

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = 'source ~/.config/nvim/plugins/denite.vim'
on_event = 'VimEnter'
if = 'has("nvim")'
if = 'has("python3")'
depends = ['neomru.vim']
