[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source ~/.config/nvim/plugins/fern.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

[[plugins]]
repo = 'kshenoy/vim-signature'
hook_add = 'source ~/.config/nvim/plugins/vim-signature.vim'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugins/vim-submode.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'source ~/.config/nvim/plugins/deol.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source ~/.config/nvim/plugins/caw.vim'

[[plugins]]
repo = 'zefei/vim-wintabs'
hook_add = 'source ~/.config/nvim/plugins/vim-wintabs.vim'

[[plugins]]
repo = 'zefei/vim-wintabs-powerline'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = 'source ~/.config/nvim/plugins/vim-vsnip.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
