[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
if = 'has("nvim")'
hook_source = 'source ~/.config/nvim/plugins/denite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite']
if = 'has("nvim")'
