[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

[[plugins]] 
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
hook_add = 'source ~/.config/nvim/plugins/deoplete.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/plugins/vim-gitgutter.vim'

[[plugins]]
repo = 'kshenoy/vim-signature'
hook_add = 'source ~/.config/nvim/plugins/vim-signate.vim'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugins/vim-submode.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'source ~/.config/nvim/plugins/deol.vim'
