[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = 'source ~/.config/nvim/plugins/vim-fugitive.vim'
on_cmd = ['Git', 'Gstatus', 'Gblame', 'Glog', 'Gread', 'Gwrite', 'Gremove']

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_source = 'source ~/.config/nvim/plugins/vim-sonictemplate.vim'
on_cmd = ['Template']

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = 'source ~/.config/nvim/plugins/vim-lsp.vim'
on_ft = 'python'
depends = ['async.vim']

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
if = 'has("python3")'
on_ft = 'python'

[[plugins]] 
repo = 'Shougo/deoplete.nvim'
hook_source = 'source ~/.config/nvim/plugins/deoplete.vim'
if = 'has("python3")'
on_ft = 'python'
depends = ['vim-lsp', 'deoplete-vim-lsp']

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = 'source ~/.config/nvim/plugins/denite.vim'
on_event = 'VimEnter'
if = 'has("nvim")'
if = 'has("python3")'
depends = ['neomru.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'
if = 'has("nvim")'

