[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

[[plugins]] 
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.config/nvim/plugins/deoplete.vim'
