call submode#enter_with('winsize', 'n', '', '<C-s>>', '<C-w>>')
call submode#enter_with('winsize', 'n', '', '<C-s><', '<C-w><')
call submode#enter_with('winsize', 'n', '', '<C-s>+', '<C-w>+')
call submode#enter_with('winsize', 'n', '', '<C-s>-', '<C-w>-')
call submode#map('winsize', 'n', '', '>', '<C-w>>')
call submode#map('winsize', 'n', '', '<', '<C-w><')
call submode#map('winsize', 'n', '', '+', '<C-w>+')
call submode#map('winsize', 'n', '', '-', '<C-w>-')
